import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Products from "./Products";

export default function Home(handleEdit) {
  return (
    <div className={styles.content}>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Products />
    </div>
  );
}
