import Head from "next/head";
<<<<<<< HEAD

export default function Home() {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="article">
        <h1>Welcome Admin</h1>
      </section>
=======
import styles from "../styles/Home.module.scss";
import Products from "./Products";

export default function Home(handleEdit) {
  return (
    <div className={styles.content}>
      <Head>
        <title>Fake Store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Products />
>>>>>>> 52d1bafaae3ddf69d0a09100bdd3d8c5629d171e
    </div>
  );
}
